[project]
name = "extract"
version = "0.1.0"
description = "Extraction of INE data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "pyarrow>=18.1.0",
]
