[project]
name = "extract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt>=1.4.0",
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
]
